spring.datasource.url=jdbc:mysql://localhost:3306/hms_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# spring-session-jdbc will handle server-side sessions
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=20m

# HTTP max session settings handled in security config

server.port=8080
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
# CSRF can be enabled for session based apps

# logging
logging.level.org.springframework.security=DEBUG
